### ISSUE TITLE
code for lvl 13 c11 does not work

### ISSUE THREAD

**Issue by idkausernamewastaken** [paenis/csa-2022#2]

**Comment by idkausernamewastaken** [comment]
code for lvl 13 c11 does not work

**Comment by idkausernamewastaken** [comment]
all of level 13 are not in the folder

**Comment by paenis** [comment]
i havent figured them out yet 👍

**Comment by idkausernamewastaken** [comment]
yeah level 13 is pain

**Comment by idkausernamewastaken** [comment]
did you try the lvl13 c11 and did it work?

**Comment by paenis** [comment]
one of the base64 strings from the challenge gives you hex when decoded but idk where to go from there

**Comment by idkausernamewastaken** [comment]
also what is the script for lvl13 ch1
